#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: branch-automation
  namespace: galasa-build
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  params:
  - name: branch
    type: string
    default: main
  - name: refspec
    type: string
    default: refs/heads/main:refs/heads/main
  workspaces:
  - name: git-workspace
  tasks:
# 
# 
# 
  - name: clone-automation
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/automation
    - name: revision
      value: $(params.branch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: $(context.pipelineRun.name)/automation
    workspaces:
     - name: output
       workspace: git-workspace
# 
#
#
  - name: apply-galasa-properties
    taskRef: 
      name: galasactl
    runAfter:
    - clone-automation
    params:
    - name: galasaHome
      value: /workspace/git/$(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/infrastructure/cicsk8s/galasa-dev
    - name: command
      value:
        - resources
        - apply
        - -f
        - cps-properties.yaml 
        - --bootstrap
        - https://prod1-galasa-dev.cicsk8s.hursley.ibm.com/api/bootstrap
    - name: galasactlImageTag
      value: stable
    workspaces:
     - name: git-workspace
       workspace: git-workspace 
# 
# 
# 
  - name: get-commit
    taskRef:
      name: get-commit
    runAfter:
    - clone-automation
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: repo
      value: automation
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  - name: go-build-ghverify
    taskRef:
      name: go-build
    runAfter:
      - clone-automation
    params:
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-verify
    - name: goArgs
      value:
      - build
      - -o
      - bin/ghverify
      - cmd/main.go  
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  - name: build-ghverify-image
    taskRef:
      name: docker-build
    runAfter:
    - go-build-ghverify
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-verify
    - name: dockerfilePath
      value: automation/dockerfiles/common/ghverify-dockerfile
    - name: imageName
      value: ghcr.io/galasa-dev/ghverify:$(params.branch)
    - name: noPush
      value: ""
    workspaces:
     - name: git-workspace
       workspace: git-workspace

  #---------------------------------------------------------------------
  # Github pull request status publisher tool
  #---------------------------------------------------------------------
  # Used in pipelines to tell the github PR whether a build passed or failed.
  - name: go-build-ghstatus
    taskRef:
      name: go-build
    runAfter:
      - clone-automation
    params:
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-status
    - name: goArgs
      value:
      - build
      - -o
      - bin/ghstatus
      - cmd/main.go  
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  - name: build-ghstatus-image
    taskRef:
      name: docker-build
    runAfter:
    - go-build-ghstatus
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-status
    - name: dockerfilePath
      value: automation/dockerfiles/common/ghstatus-dockerfile
    - name: imageName
      value: ghcr.io/galasa-dev/ghstatus:$(params.branch)
    - name: noPush
      value: ""
    workspaces:
     - name: git-workspace
       workspace: git-workspace

  #---------------------------------------------------------------------
  # Github activity monitor
  #---------------------------------------------------------------------
  # Build a tool which monitors github for webhook events which have previously
  # been delivered, and kick-off an internal pipeline to handle them.
  - name: go-build-ghmonitor
    taskRef:
      name: go-build
    runAfter:
      - clone-automation
    params:
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-webhook-monitor
    - name: goArgs
      value:
      - build
      - -o
      - bin/ghmonitor
      - cmd/main.go  
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  - name: build-ghmonitor-image
    taskRef:
      name: docker-build
    runAfter:
    - go-build-ghmonitor
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-webhook-monitor
    - name: dockerfilePath
      value: automation/dockerfiles/common/github-monitor-dockerfile
    - name: imageName
      value: ghcr.io/galasa-dev/ghmonitor:$(params.branch)
    - name: noPush
      value: ""
    workspaces:
     - name: git-workspace
       workspace: git-workspace  


  #---------------------------------------------------------------------
  # Github webhook receiver
  #---------------------------------------------------------------------
  # A tool which is called by the webhook, responds OK, and 
  # tells a pull request that a build is 'pending...'
  #
  # Build the go code.
  - name: go-build-ghreceiver
    taskRef:
      name: go-build
    runAfter:
      - clone-automation
    params:
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-webhook-receiver
    - name: goArgs
      value:
      - build
      - -o
      - bin/ghreceiver
      - cmd/github-webhook-receiver/main.go  
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# Build the docker image (and push it to harbor)
# 
# 
  - name: build-ghreceiver-image
    taskRef:
      name: docker-build
    runAfter:
    - go-build-ghreceiver
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/build-images/github-webhook-receiver
    - name: dockerfilePath
      value: automation/dockerfiles/common/github-receiver-dockerfile
    - name: imageName
      value: ghcr.io/galasa-dev/ghreceiver:$(params.branch)
    - name: noPush
      value: ""
    workspaces:
     - name: git-workspace
       workspace: git-workspace  

  #---------------------------------------------------------------------
  # tkn cli tool - control tekton from within a tekton pipeline
  #---------------------------------------------------------------------
  # Package the tool into a docker image
  - name: build-tkn-image
    taskRef:
      name: docker-build
    runAfter:
    - clone-automation
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/pipelines/templates
    - name: dockerfilePath
      value: automation/dockerfiles/common/tkn-dockerfile
    - name: imageName
      value: ghcr.io/galasa-dev/tkn:$(params.branch)
    - name: noPush
      value: ""
    workspaces:
     - name: git-workspace
       workspace: git-workspace  

  finally:
  - name: report-failed-build
    when:
      - input: "$(tasks.status)"
        operator: in
        values: ["Failed"]
    taskRef:
      name: slack-post
    params:
    - name: pipelineName
      value: $(context.pipeline.name)
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: branch
      value: $(params.branch)
