#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: delete-branches-galasa-
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  pipelineRef:
    name: branch-delete-all
  podTemplate:
    volumes:
    - name: githubcreds
      secret:
        secretName: github-token
    - name: harborcreds
      secret:
        secretName: harbor-creds-yaml
    - name: mavencreds
      secret:
        secretName: maven-creds
  params:
  - name: distBranch
    value: "release"