#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-tls
  namespace: galasa-ecosystem1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ibmcloud-secrets-manager
    kind: SecretStore
  target:
    name: galasa-wildcard-cert
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      property: certificate
      key: imported_cert/dce33b75-c081-75b5-38dd-9ebb859ec298
  - secretKey: tls.key
    remoteRef:
      property: private_key
      key: imported_cert/dce33b75-c081-75b5-38dd-9ebb859ec298
