#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

# This EventListener gets called when pushes are made to the 'main'
# branch of the https://github.com/galasa-dev/automation repository.

# It calls the Tekton Pipeline 'branch-automation'. This pipeline's
# job is to apply CPS properties from a file checked into the repo
# to the prod1 Galasa service's CPS with `galasactl resources apply`

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-main-builder-listener
  annotations:
    tekton.dev/payload-validation: "false"
spec:
  serviceAccountName: tekton-trigger
  triggers:
    - name: gitlab-push-events-trigger
      interceptors:
        - name: "validate GitHub payload and filter on eventType"
          ref:
            name: "github"
          params:
          - name: "eventTypes"
            value: ["push"]
        - name: "CEL filter: only when pushed to main"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/main']"
        - name: "CEL filter: only when the workflow was for the automation repository"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.repository.name in ['automation']"

      bindings:
        - name: git-repository-name
          value: $(body.repository.name)
       
      template:
        spec:
          params:
            - name: git-repository-name
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: repo-$(tt.params.git-repository-name)-main-
              spec:
                pipelineRef:
                  name: branch-$(tt.params.git-repository-name)
                serviceAccountName: galasa-build-bot
                podTemplate:
                  volumes:
                  - name: gradle-properties
                    secret:
                      secretName: gradle-properties
                  - name: gpg-key
                    secret:
                      secretName: gpg-key
                  - name: githubcreds
                    secret:
                      secretName: github-token
                workspaces:
                - name: git-workspace
                  volumeClaimTemplate:
                    spec:
                      storageClassName: longhorn-temp
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 20Gi