#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: galasabld
  namespace: galasa-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: context
    type: string
  - name: command
    type: array
  - name: galasabldImageTag
    type: string
    default: main
  - name: image
    type: string
    default: ghcr.io/galasa-dev/galasabld-amd64
  steps:
  - name: galasabld
    workingDir: /workspace/git/$(params.context)
    image: $(params.image):$(params.galasabldImageTag)
    imagePullPolicy: Always
    command:
    - galasabld
    - $(params.command[*])
    volumeMounts:
    - name: githubcreds
      mountPath: /creds