#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: general-command
  namespace: galasa-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params: 
  - name: context
    type: string
  - name: command
    type: array
  - name: image
    type: string  
    default: ghcr.io/galasa-dev/busybox:1.36.1
  steps:
  - name: run-command
    workingDir: /workspace/git/$(params.context)
    image: $(params.image)
    imagePullPolicy: IfNotPresent
    command:
      - $(params.command[*])