#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helm
  namespace: galasa-build
spec:
  workspaces:
  params:
  - name: command
    type: array
  steps:
  - name: helm
    image: ghcr.io/galasa-dev/helm:main
    imagePullPolicy: IfNotPresent
    args:
    - $(params.command)
