#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl
  namespace: galasa-build
spec:
  params:
  - name: command
    type: array       
  steps:
  - name: kubectl
    image: ghcr.io/galasa-dev/kubectl:main
    imagePullPolicy: IfNotPresent
    args:
    - $(params.command)