#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: make-with-params
  namespace: galasa-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: directory
    type: string  
  - name: command
    type: array
    default: 
    - all
  steps:
  - name: make
    workingDir: /workspace/git/$(params.directory)
    image: harbor.galasa.dev/docker_proxy_cache/library/golang:1.20.1
    imagePullPolicy: IfNotPresent
    command: 
      - make
      - $(params.command[*])
