#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-gpg
  namespace: galasa-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: context
    type: string  
  - name: settingsDirectory
    type: string
    default: /workspace/git/gpg
  steps:
  - name: gpgdirectory
    workingDir: /workspace/git/$(params.context)
    image: ghcr.io/galasa-dev/busybox:1.36.1
    imagePullPolicy: IfNotPresent
    command:
    - mkdir
    - $(params.settingsDirectory)
  - name: change-dir-permissions
    workingDir: /workspace/git/$(params.context)
    image: ghcr.io/galasa-dev/gpg:main
    imagePullPolicy: IfNotPresent
    command:
    - chmod
    - '700'
    - $(params.settingsDirectory)
  - name: import-gpg
    workingDir: /workspace/git/$(params.context)
    image: ghcr.io/galasa-dev/gpg:main
    imagePullPolicy: IfNotPresent
    command:
    - gpg
    - --homedir
    - $(params.settingsDirectory)
    - --pinentry-mode
    - loopback
    - --passphrase-file
    - /root/mavengpg/galasa.passphrase
    - --import
    - /root/mavengpg/galasa.gpg
    volumeMounts:
    - name: mavengpg
      mountPath: /root/mavengpg
  - name: copy-settings
    workingDir: /workspace/git/$(params.context)
    image: ghcr.io/galasa-dev/busybox:1.36.1
    imagePullPolicy: IfNotPresent
    command:
    - cp
    - /root/mavengpg/settings.xml
    - $(params.settingsDirectory)/settings.xml
    volumeMounts:
    - name: mavengpg
      mountPath: /root/mavengpg