#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: script
  namespace: galasa-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: context
    type: string
  - name: script
    type: string
  - name: image
    type: string
    default: harbor.galasa.dev/docker_proxy_cache/library/busybox:1.36.1
  steps:
  - name: script
    workingDir: /workspace/git/$(params.context)
    image: $(params.image)
    imagePullPolicy: IfNotPresent
    script: |
      #!/bin/sh
      set +e
      $(params.script)