#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tkn-cli
  namespace: galasa-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: context
    type: string
  - name: command
    type: array
  steps:
  - name: tkn-cli
    workingDir: /workspace/git/$(params.context)
    image: ghcr.io/galasa-dev/tkn:main
    imagePullPolicy: IfNotPresent
    command:
      - tkn
      - $(params.command[*])