#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivts-{{ .Values.branch }}
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ivts-{{ .Values.branch }}
  template:
    metadata:
      name: ivts-{{ .Values.branch }}
      labels:
        app: ivts-{{ .Values.branch }}
    spec:
      containers:
        - image: {{ .Values.imageName }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          name: ivts-{{ .Values.branch }}
          env:
          - name: CONTEXTROOT
            value: {{ .Values.branch }}/maven-repo/{{ .Values.ingress.pathSuffix }}
          ports:
            - containerPort: 80