#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ivts-{{ .Values.branch }}
  name: ivts-{{ .Values.branch }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
  selector:
    app: ivts-{{ .Values.branch }}