#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

# This is a token that is used to authenticate to argocd.galasa.dev
# in the Task argocd-cli in the build pipelines that recycles applications.

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:  
  name: argocd-token
  namespace: galasa-build
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-token
    template:
      type: Opaque
          
  data:
  - secretKey: argocd-token
    remoteRef:
      property: argocd-token
      key: galasa-secrets/argocd-token
