#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:  
  name: ghcr-authentication
  namespace: galasa-build
  annotations:
    tekton.dev/docker-0: https://ghcr.io
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ghcr-authentication
    template:
      metadata:
        annotations:
          tekton.dev/docker-0: https://ghcr.io
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}" #Not a secret but logic for a kube secret #pragma: allowlist secret 

         
  data:
  - secretKey: username
    remoteRef:
      property: username
      key: galasa-secrets/github-token-read-packages
  - secretKey: password
    remoteRef:
      property: password
      key: galasa-secrets/github-token-read-packages
