#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: githubmonitor-configmap
  namespace: galasa-build
data: 
  config.yaml: |
    events:
      push:
        eventListener: ["http://el-github-main-builder-listener.galasa-build.svc.cluster.local:8080"]
      workflow_run:
        eventListener: ["http://el-github-webui-workflow-completed-listener.galasa-build.svc.cluster.local:8080","http://el-github-galasa-monorepo-workflow-completed-listener.galasa-build.svc.cluster.local:8080"]