#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

# This is a token that is used to authenticate to the IBM Event Streams instance.

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:  
  name: event-streams-token
  namespace: galasa-dev
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: event-streams-token
    template:
      type: Opaque
          
  data:
  - secretKey: GALASA_EVENT_STREAMS_TOKEN
    remoteRef:
      key: galasa-secrets/event-streams-token
      property: token
