#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: branch-buildutils
  namespace: galasa-build
spec:
  params:
  - name: branch
    type: string
    default: main
  - name: refspec
    type: string
    default: refs/heads/main:refs/heads/main
  - name: imageTag
    type: string
    default: main
  - name: appname
    type: string
    default: main-bld
  workspaces:
  - name: git-workspace
# 
# 
#
  tasks:
  - name: clone-automation
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/automation
    - name: revision
      value: main
    - name: refspec
      value: refs/heads/main:refs/heads/main
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: $(context.pipelineRun.name)/automation
    workspaces:
     - name: output
       workspace: git-workspace
# 
# 
#
  - name: clone-buildutils
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/buildutils
    - name: revision
      value: $(params.branch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: $(context.pipelineRun.name)/buildutils
    workspaces:
     - name: output
       workspace: git-workspace 
# 
# 
#
  - name: make
    taskRef:
      name: make-with-params
    runAfter:
      - clone-buildutils  
    params:
    - name: directory
      value: $(context.pipelineRun.name)/buildutils
    workspaces:
     - name: git-workspace
       workspace: git-workspace 
# 
# 
#
  - name: make-openapi2beans
    taskRef:
      name: make-with-params
    runAfter:
      - clone-buildutils  
    params:
    - name: directory
      value: $(context.pipelineRun.name)/buildutils/openapi2beans
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  - name: build-buildutils-binary-downloadables
    taskRef:
      name: docker-build
    runAfter:
    - clone-automation
    - make
    - make-openapi2bean
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)
    - name: dockerfilePath
      value: automation/dockerfiles/buildutils/buildutils-binary-dockerfile
    - name: imageName
      value: harbor.galasa.dev/galasadev/buildutils-binary-downloadables:$(params.imageTag)
    - name: noPush
      value: ""
    - name: buildArgs
      value:
        - "--build-arg=branch=$(params.branch)"
    workspaces:
     - name: git-workspace
       workspace: git-workspace 
# 
# 
# 
  - name: recycle-buildutils-binaries
    taskRef:
      name: argocd-cli
    runAfter:
    - build-buildutils-binary-downloadables
    params:
    - name: server
      value: argocd.galasa.dev
    - name: command
      value: 
      - app 
      - actions 
      - run 
      - $(params.appname)
      - restart 
      - --kind 
      - Deployment
      - --resource-name
      - bld-$(params.imageTag)
# 
# 
# 
  - name: build-galasabld-executable
    taskRef:
      name: docker-build
    runAfter:
    - make
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/buildutils
    - name: dockerfilePath
      value: automation/dockerfiles/galasabld/galasabld-dockerfile
    - name: imageName
      value: harbor.galasa.dev/galasadev/galasabld-amd64:$(params.imageTag)
    - name: noPush
      value: ""
    - name: buildArgs
      value:
        - "--build-arg=platform=linux-amd64"
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  - name: build-galasabld-ibm-executable
    taskRef:
      name: docker-build
    runAfter:
    - build-galasabld-executable
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/automation/dockerfiles/certs
    - name: dockerfilePath
      value: automation/dockerfiles/galasabld/galasabld-ibm-dockerfile
    - name: imageName
      value: harbor.galasa.dev/galasadev/galasabld-ibm-amd64:$(params.imageTag)
    - name: noPush
      value: ""
    - name: buildArgs
      value:
        - "--build-arg=dockerRepository=harbor.galasa.dev"
        - "--build-arg=branch=$(params.imageTag)"
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# builds openapi2beans to a dockerfile
  - name: build-openapi2beans-executable
    taskRef:
      name: docker-build
    runAfter:
    - make-openapi2beans
    - clone-automation
    params:
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: context
      value: $(context.pipelineRun.name)/buildutils/openapi2beans
    - name: dockerfilePath
      value: automation/dockerfiles/openapi2beans/openapi2beans-dockerfile
    - name: imageName
      value: harbor.galasa.dev/galasadev/openapi2beans-amd64:$(params.imageTag)
    - name: noPush
      value: ""
    - name: buildArgs
      value:
        - "--build-arg=platform=linux-amd64"
    workspaces:
     - name: git-workspace
       workspace: git-workspace
# 
# 
# 
  finally:
  - name: report-failed-build
    when:
      - input: "$(tasks.status)"
        operator: in
        values: ["Failed"]
    taskRef:
      name: slack-post
    params:
    - name: pipelineName
      value: $(context.pipeline.name)
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    - name: branch
      value: $(params.branch)
