#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

# These Pipelines essentially do nothing but they are to avoid
# a CouldntGetPipeline error from the EventListener attempting
# to call the pipelines with pr-* and branch-*.

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pr-galasa.dev
  namespace: galasa-build
  # Tell ArgoCD never to prune this pipeline definition.
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: headRef
    type: string
  - name: headSha
    type: string
  - name: baseRef
    type: string
  - name: prUrl
    type: string
  - name: statusesUrl
    type: string
  - name: issueUrl
    type: string
  - name: userId
    type: string
  - name: prNumber
    type: string
  - name: action
    type: string

---

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: branch-galasa.dev
  namespace: galasa-build
  # Tell ArgoCD never to prune this pipeline definition.
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  workspaces:
  - name: git-workspace

