#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: run-ivts-prod1
  namespace: galasa-build
spec:
#
#
#
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: bootVersion
    type: string
#
#
#
  tasks:
#
#
#
  - name: run-cicsts-tests
    taskRef: 
      name: galasactl
    params:
    - name: context
      value: $(context.pipelineRun.name)
    - name: galasaHome
      value: /workspace/git/$(context.pipelineRun.name)
    - name: command
      value: 
        - runs
        - submit
        - --bootstrap
        - https://prod1-galasa-dev.cicsk8s.hursley.ibm.com/api/bootstrap
        - --stream
        - ivts
        # Overrides the current CPS property which says to use SEM.
        - --override
        - cicsts.provision.type=dse
        # Select the CICS tests with the --class flag.
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.cicsts.CICSTSManagerIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.cemt.CEMTManagerIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.ceda.CedaManagerIVT
        # Currently not set up - will add in when it is...
        # - --class
        # - dev.galasa.zos.ivts/dev.galasa.zos.ivts.ceci.CECIManagerIVT
        - --throttle
        - '10'
        - --poll
        - '10'
        - --progress
        - '1'
        - --trace
        - --log # Otherwise there is no output
        - "-"
# 
# 
# 
  - name: run-zos-tests
    runAfter:
      - run-cicsts-tests
    taskRef: 
      name: galasactl
    params:
    - name: context
      value: $(context.pipelineRun.name)
    - name: galasaHome
      value: /workspace/git/$(context.pipelineRun.name)
    - name: command
      value: 
        - runs
        - submit
        - --bootstrap
        - https://prod1-galasa-dev.cicsk8s.hursley.ibm.com/api/bootstrap
        - --stream
        - ivts
        # Select the z/OS tests with the --class flag.
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos3270.Zos3270IVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerTSOCommandIVT
        - --throttle
        - '10'
        - --poll
        - '10'
        - --progress
        - '1'
        - --trace
        - --log # Otherwise there is no output
        - "-"
# 
# 
# 
  - name: run-zos-mf-tests
    runAfter:
      - run-zos-tests
    taskRef: 
      name: galasactl
    params:
    - name: context
      value: $(context.pipelineRun.name)
    - name: galasaHome
      value: /workspace/git/$(context.pipelineRun.name)
    - name: command
      value: 
        - runs
        - submit
        - --bootstrap
        - https://prod1-galasa-dev.cicsk8s.hursley.ibm.com/api/bootstrap
        - --stream
        - ivts
        # Tells the IVTs to use the z/OS MF implementation of the z/OS Manager.
        - --override
        - zos.bundle.extra.batch.manager=dev.galasa.zosbatch.zosmf.manager
        # Select the z/OS MF tests with the --class flag.
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerBatchIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerFileIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerFileDatasetIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerFileVSAMIVT
        - --throttle
        - '10'
        - --poll
        - '10'
        - --progress
        - '1'
        - --trace
        - --log # Otherwise there is no output
        - "-"
# 
# 
# 
  - name: run-rse-api-tests
    runAfter:
      - run-zos-mf-tests
    taskRef: 
      name: galasactl
    params:
    - name: context
      value: $(context.pipelineRun.name)
    - name: galasaHome
      value: /workspace/git/$(context.pipelineRun.name)
    - name: command
      value: 
        - runs
        - submit
        - --bootstrap
        - https://prod1-galasa-dev.cicsk8s.hursley.ibm.com/api/bootstrap
        - --stream
        - ivts
        # Tells the IVTs to use the RSE API implementation of the z/OS Manager.
        - --override
        - zos.bundle.extra.batch.manager=dev.galasa.zosbatch.rseapi.manager
        # Select the RSE API tests with the --class flag.
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerBatchIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerFileIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerFileDatasetIVT
        - --class
        - dev.galasa.zos.ivts/dev.galasa.zos.ivts.zos.ZosManagerFileVSAMIVT
        - --throttle
        - '10'
        - --poll
        - '10'
        - --progress
        - '1'
        - --trace
        - --log # Otherwise there is no output
        - "-"