#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

# These values are overridden in the ArgoCD app.

namespace: galasa-build
branch: main
imageName: ghcr.io/galasa-dev/base-image
imageTag: latest

ingress:
  externalHostname: development.galasa.dev
  ingressClassName: public-iks-k8s-nginx
  tls:
  - hosts:
      - development.galasa.dev
    secretName: galasa-wildcard-cert
