name: build-base-image
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  NAMESPACE: galasa-dev

jobs:
  build-base-image:
    name: Build the base httpd image for hosting the development Maven registries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
            context: .
            file: dockerfiles/base/base-dockerfile
            push: true
            tags: base-image:latest
