name: branch-create-galasa

on:
    workflow_dispatch:
        inputs:
            distBranch:
                description: 'Destination branch'
                required: true
            fromBranch:
                description: 'Source branch'
                required: true
            overwrite:
                description: 'Overwrite destination branch'
                required: false
                default: ''
            force:
                description: 'Force copy'
                required: false
                default: ''

jobs:
    branch-create-galasa:
      strategy:
        matrix:
          repo: ['automation', 'galasa', 'cli', 'isolated', 'helm', 'webui', 'simplatform']
      runs-on: ubuntu-latest
      steps:
        - name: Make secrets directory
          run: |
            mkdir -p /home/runner/work/secrets
            echo ${{ secrets.GITHUB_CREDENTIALS }} > /home/runner/work/secrets/githubcreds.yaml

        - name: Clone branch ${{ matrix.repo }}
          run: |
            docker run ghcr.io/galasa-dev/galasabld-amd64:main github branch copy \
            --repository ${{ matrix.repo }} --to ${{ inputs.distBranch }} \
            --branch ${{ inputs.fromBranch }} ${{ inputs.overwrite }} ${{ inputs.force }} \
            --credentials /home/runner/work/secrets/githubcreds.yaml