#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Deploy to Staging Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: "galasa release version, should be of the form x.xx.x"
        required: true
      repository:
        description: "maven deployment repository"
        required: false
        default: 'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2'

jobs:
  deploy-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Maven artifacts to Staging Repository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          docker run ghcr.io/galasa-dev/obr-with-galasabld-executable:release maven deploy \
          --repository ${{ inputs.repository }} --local /usr/local/apache2/htdocs \
          --group dev.galasa --version ${{ inputs.version }} \
          --username "${{ env.SONATYPE_USERNAME }}" \
          --password "${{ env.SONATYPE_PASSWORD }}"
